### PR TITLE
Attributes

### PR DESCRIPTION
**Pull request by arielelkin**
Addresses https://github.com/SimonFairbairn/SwiftyMarkdown/issues/16 and https://github.com/SimonFairbairn/SwiftyMarkdown/pull/12

The idea here is to let users define `NSAttributedString` attributes for individual styles and default to Dynamic Typing if these are not set. This provides much needed flexibility without giving up Dynamic Typing. 

To see this in action, open `SwiftyMarkdown.playground` and compare `Dynamic Typing` with `Attributes`:

## Attributes
image

## Dynamic Typing
image

Feedback and comments welcome.

### CODE REVIEW

**Comment by arielelkin** [comment]
Following from https://twitter.com/AriVocals/status/736176963463880704

@SimonFairbairn says:
> I'd rather add more attribute support via explicit properties in the protocol. Don't have to look up attributed string keys.

As you probably know, UIKit defines more than thirty keys corresponding to character attributes, paragraph styles, and underline styles; would it actually be productive to write and maintain a wrapper for every one of them?

This is also why I removed the `FontProperties` protocol; it's just duplicating the functionality of the default attributed string keys defined by UIKit.

**Comment by mschonvogel** [comment]
@SimonFairbairn merge?

**Comment by arielelkin** [comment]
@SimonFairbairn this PR has been opened for several weeks now, would be good to have your input on it.

**Comment by SimonFairbairn** [comment]
I appreciate the effort, but, as I explained on Twitter, I have no interest in exposing NSAttributedString attributes directly to users. I'd rather add additional properties to the protocol. 

The current tight coupling between the parser and using attributed strings is an implementation detail that the API consumer need not know about. Exposing the attributed string properties to the user further tightens that coupling while also making the API less intuitive and easy to use. 

As it stands, I could rewrite the parser to support, for example, SKLabelNodes (which also support custom fonts and colours) without having to change any of the current API and only adding one additional method to pass back the formatted nodes.

Then there's code completion. Xcode only has to show the available properties for each paragraph style, so even if you don't remember what's available to you as a user, you can see the complete list by tapping `h1.` and as soon as you hit that period, it'll show just those properties available instead of every string constant. 

That's partly what makes this Swifty—leveraging the protocol features of Swift to make it faster to write.

I understand that this comes at the expense of the advanced functionality available in NSAttributedString, but we can add properties back in as and when they are required.

Secondly, the fact that it outputs an attributed string is also relatively arbitrary. It could very easily output HTML and CSS or an image or rich text in future. 

By allowing users to define all of the properties available to NSAttributedString, I'm promising to support them even in future outputs that either don't need them or would require additional work to support them.

**Comment by arielelkin** [comment]
https://github.com/SimonFairbairn/SwiftyMarkdown/pull/19

**Pull request closed without merging**
