### PR TITLE
Add fixed font size for type and support Objc

### PR DESCRIPTION
**Pull request by lucasromanomr**
Added option to set font size for each type of text. Support for objc has also been added

### CODE REVIEW

**Comment by lucasromanomr** [comment]
Modifications made and adjusted.
Was added:
* Support for objc
* Ability to add a specific font size
* Ability to set font, color and font size for all Styles

**Comment by SimonFairbairn** [comment]
Great work, thanks very much.

**Comment by SimonFairbairn** [comment]
@lucasromanomr Any reason why this was commented out? 

I'll go ahead and roll it back in the meantime.

**Comment by SimonFairbairn** [comment]
The extra line break is how the library has always worked. 

Now that you mention it, though, there is no good reason for it. Looking over the tests, I see that I am testing for that additional line break and I can't understand what I was thinking because I left myself no comments and no notes in the documentation.

My younger self is useless and should have his GitHub credentials revoked immediately. 

Anyway, I'll update all the tests and then push out a new minor version and then I will cross my fingers like a professional. 

Thanks!

**Pull request merged**
