### PR TITLE
adds support for optionally setting a fixed font size

### PR DESCRIPTION
**Pull request by mightea**
Sometimes you just need to fix the font size for design purposes. This PR adds the ability to override the dynamic text font size by setting the fontSize on the respective `FontProperties`.

### CODE REVIEW

**Comment by ranunez** [comment]
This looks nice, but I would fix some obvious indentation issues

**Comment by mightea** [comment]
it's fixed, I didn't see this in XCode, my bad

**Comment by jdivittorio3** [comment]
Thanks for doing this. Any idea when this might go in?

**Comment by SimonFairbairn** [comment]
I'm still considering it. I appreciate the effort but I'm not looking to add additional complexity unnecessarily. I think the main use case for this is for larger, multi-line text areas which have less of a reason not to support dynamic type and making dynamic type the default is a significant accessibility win.

**Comment by QuentinArnault** [comment]
I'm interested by this Pull Requests.

**Comment by QuentinArnault** [comment]
__Test__

**Comment by QuentinArnault** [comment]
<u>hkljh</u>

**Comment by bsmith11** [comment]
I'm needing this PR as well

**Comment by arielelkin** [comment]
@SimonFairbairn:

> making dynamic type the default is a significant accessibility win

I agree. But that's not a reason for _not_ allowing developers to override it.

**Comment by patthehuman** [comment]
Will this ever get merged?

**Comment by MrAlek** [comment]
We need this for our app too. It's a big assumption to make that markdown is used for large text bodies. For us, it is not the case.

**Pull request closed without merging**
